const PROGRAM=[
{id:"A",name:"Corps complet A",focus:"Accent haut du dos",duration:"50–60 min",exercises:[
{id:"leg_press",name:"Presse à jambes",sets:3,minReps:8,maxReps:12,rest:120,type:"strength"},
{id:"machine_chest_press",name:"Développé poitrine à la machine",sets:3,minReps:8,maxReps:12,rest:90,type:"strength"},
{id:"supported_row",name:"Rowing poitrine appuyée",sets:3,minReps:8,maxReps:12,rest:90,type:"strength",note:"Garde le cou neutre et évite de hausser les épaules."},
{id:"lat_pulldown",name:"Tirage vertical",sets:2,minReps:8,maxReps:12,rest:90,type:"strength"},
{id:"lateral_raise",name:"Élévations latérales",sets:2,minReps:12,maxReps:15,rest:60,type:"strength"},
{id:"biceps_curl",name:"Curl biceps",sets:2,minReps:10,maxReps:15,rest:60,type:"strength"},
{id:"triceps_pushdown",name:"Extension triceps à la poulie",sets:2,minReps:10,maxReps:15,rest:60,type:"strength"},
{id:"bike",name:"Vélo",durationMinutes:8,type:"cardio",note:"Intensité modérée. Tu dois pouvoir parler en phrases courtes."}]},
{id:"B",name:"Corps complet B",focus:"Posture • épaules • jambes",duration:"50–60 min",exercises:[
{id:"hack_squat",name:"Hack squat",sets:3,minReps:8,maxReps:12,rest:120,type:"strength"},
{id:"leg_curl",name:"Leg curl assis",sets:3,minReps:10,maxReps:15,rest:90,type:"strength"},
{id:"incline_press",name:"Développé incliné avec haltères",sets:3,minReps:8,maxReps:12,rest:90,type:"strength"},
{id:"cable_row",name:"Rowing assis à la poulie",sets:3,minReps:8,maxReps:12,rest:90,type:"strength",note:"Ne pousse pas la tête vers l’avant pendant le tirage."},
{id:"reverse_pec_deck",name:"Reverse pec deck",sets:2,minReps:12,maxReps:15,rest:60,type:"strength"},
{id:"lateral_raise_b",name:"Élévations latérales",sets:2,minReps:12,maxReps:15,rest:60,type:"strength"},
{id:"bird_dog",name:"Bird dog",sets:2,minReps:8,maxReps:8,rest:45,type:"strength"},
{id:"neck_isometrics",name:"Isométriques cervicaux légers",sets:3,minReps:5,maxReps:10,rest:30,type:"strength",note:"Pression très légère contre la main. Arrête si cela reproduit clairement tes maux de tête ou tes douleurs."}]},
{id:"C",name:"Corps complet C",focus:"Dos • chaîne postérieure",duration:"50–60 min",exercises:[
{id:"leg_press_c",name:"Presse à jambes",sets:3,minReps:10,maxReps:12,rest:120,type:"strength"},
{id:"romanian_deadlift",name:"Soulevé de terre roumain avec haltères",sets:2,minReps:8,maxReps:12,rest:120,type:"strength",note:"Commence léger et apprends d’abord le mouvement."},
{id:"machine_chest_press_c",name:"Développé poitrine à la machine",sets:3,minReps:8,maxReps:12,rest:90,type:"strength"},
{id:"supported_row_c",name:"Rowing poitrine appuyée",sets:3,minReps:8,maxReps:12,rest:90,type:"strength"},
{id:"lat_pulldown_c",name:"Tirage vertical",sets:2,minReps:8,maxReps:12,rest:90,type:"strength"},
{id:"reverse_pec_deck_c",name:"Reverse pec deck",sets:2,minReps:12,maxReps:15,rest:60,type:"strength"},
{id:"hammer_curl",name:"Curl marteau",sets:2,minReps:10,maxReps:15,rest:60,type:"strength"},
{id:"triceps_pushdown_c",name:"Triceps à la poulie",sets:2,minReps:10,maxReps:15,rest:60,type:"strength"},
{id:"bike_c",name:"Vélo",durationMinutes:8,type:"cardio"}]}
];
const DEFAULT_STATE={currentPage:"home",unit:"lb",workoutHistory:[],activeWorkout:null,timer:null};
let state=loadState();
const main=document.getElementById("mainContent"),title=document.getElementById("pageTitle"),modalRoot=document.getElementById("modalRoot");
function loadState(){const saved=localStorage.getItem("stronger_state");if(!saved)return structuredClone(DEFAULT_STATE);try{return {...structuredClone(DEFAULT_STATE),...JSON.parse(saved)}}catch{return structuredClone(DEFAULT_STATE)}}
function saveState(){localStorage.setItem("stronger_state",JSON.stringify(state))}
function formatDate(timestamp){return new Date(timestamp).toLocaleDateString("fr-CA",{year:"numeric",month:"long",day:"numeric"})}
function getWorkoutById(id){return PROGRAM.find(w=>w.id===id)}
function getCompletedThisWeek(){const now=new Date(),day=now.getDay(),mondayOffset=day===0?-6:1-day,monday=new Date(now);monday.setDate(now.getDate()+mondayOffset);monday.setHours(0,0,0,0);return state.workoutHistory.filter(w=>w.completedAt>=monday.getTime())}
function getNextWorkout(){if(!state.workoutHistory.length)return PROGRAM[0];const last=state.workoutHistory[state.workoutHistory.length-1],index=PROGRAM.findIndex(w=>w.id===last.workoutId);return PROGRAM[(index+1)%PROGRAM.length]}
function setPage(page){state.currentPage=page;saveState();document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.page===page));render()}
document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>setPage(b.dataset.page)));document.getElementById("settingsButton").addEventListener("click",openSettings);
function render(){if(state.activeWorkout){renderActiveWorkout();return}switch(state.currentPage){case"program":renderProgram();break;case"history":renderHistory();break;case"progress":renderProgress();break;default:renderHome()}}
function renderHome(){title.textContent="Aujourd’hui";const next=getNextWorkout(),completed=getCompletedThisWeek().length;main.innerHTML=`<section class="card hero-card"><div class="hero-label">PROCHAINE SÉANCE</div><div class="hero-title">${next.name}</div><div class="hero-subtitle">${next.focus}<br>⏱ ${next.duration}</div><button class="primary-button" onclick="startWorkout('${next.id}')">COMMENCER LA SÉANCE</button></section><h2 class="section-title">Cette semaine</h2><section class="card"><strong>${Math.min(completed,3)} / 3 séances</strong><div class="week-progress">${[0,1,2].map(i=>`<div class="week-dot ${i<completed?"complete":""}"></div>`).join("")}</div></section><div class="metric-grid"><div class="metric"><div class="metric-value">${state.workoutHistory.length}</div><div class="metric-label">Séances complétées</div></div><div class="metric"><div class="metric-value">${getPersonalRecordCount()}</div><div class="metric-label">Meilleures charges</div></div></div><h2 class="section-title">Objectif</h2><section class="card"><strong>💪 Développement musculaire</strong><p class="hero-subtitle">Corps complet avec priorité au haut du dos, au cou et à la posture.</p><div class="warning">Les exercices cervicaux doivent rester légers. Une douleur marquée, des étourdissements, des engourdissements ou un déclenchement clair de tes maux de tête sont une raison d’arrêter l’exercice concerné.</div></section>`}
function renderProgram(){title.textContent="Programme";main.innerHTML=`<div class="workout-list">${PROGRAM.map(w=>`<div class="workout-card"><div class="workout-card-header"><div><div class="workout-name">${w.name}</div><div class="workout-focus">${w.focus}</div></div><span class="badge">${w.id}</span></div><p class="hero-subtitle">${w.exercises.length} exercices • ${w.duration}</p><button class="secondary-button" onclick="viewWorkout('${w.id}')">VOIR LA SÉANCE</button><button class="primary-button" onclick="startWorkout('${w.id}')">COMMENCER</button></div>`).join("")}</div>`}
function viewWorkout(id){const w=getWorkoutById(id);modalRoot.innerHTML=`<div class="modal-overlay" onclick="closeModal(event)"><div class="modal"><div class="modal-handle"></div><h2>${w.name}</h2><p class="hero-subtitle">${w.focus}</p>${w.exercises.map(e=>`<div class="exercise-card"><div class="exercise-title">${e.name}</div>${e.type==="cardio"?`<div class="exercise-meta">🚴 ${e.durationMinutes} minutes</div>`:`<div class="exercise-meta">${e.sets} séries × ${e.minReps}–${e.maxReps} • repos ${e.rest}s</div>`}${e.note?`<div class="exercise-note">${e.note}</div>`:""}</div>`).join("")}<button class="primary-button" onclick="startWorkout('${id}')">COMMENCER</button></div></div>`}
function closeModal(event){if(event.target.classList.contains("modal-overlay"))modalRoot.innerHTML=""}
function startWorkout(id){const w=getWorkoutById(id);state.activeWorkout={workoutId:id,startedAt:Date.now(),exercises:w.exercises.map(e=>({exerciseId:e.id,cardioCompleted:false,sets:e.type==="strength"?Array.from({length:e.sets},()=>({weight:"",reps:"",completed:false})):[]}))};modalRoot.innerHTML="";saveState();renderActiveWorkout()}
function renderActiveWorkout(){const session=state.activeWorkout,w=getWorkoutById(session.workoutId);title.textContent=w.name;main.innerHTML=`<div class="hero-subtitle">${w.focus}</div><div id="exerciseList">${w.exercises.map((e,i)=>renderExercise(e,i)).join("")}</div>${state.timer?renderTimer():""}<button class="primary-button" onclick="finishWorkout()">TERMINER LA SÉANCE</button><button class="secondary-button danger-button" onclick="cancelWorkout()">ANNULER</button>`;if(state.timer)updateTimerDisplay()}
function renderExercise(e,i){const active=state.activeWorkout.exercises[i];if(e.type==="cardio")return `<section class="exercise-card"><div class="exercise-title">🚴 ${e.name}</div><div class="exercise-meta">${e.durationMinutes} minutes</div>${e.note?`<div class="exercise-note">${e.note}</div>`:""}<button class="secondary-button" onclick="toggleCardio(${i})">${active.cardioCompleted?"✓ TERMINÉ":"MARQUER COMME TERMINÉ"}</button></section>`;const previous=findPreviousExercise(e.id);return `<section class="exercise-card"><div class="exercise-title">${e.name}</div><div class="exercise-meta">${e.sets} × ${e.minReps}–${e.maxReps} • repos ${e.rest}s</div><div class="previous">${previous?`Dernière séance : ${previous}`:"Première séance"}</div>${e.note?`<div class="exercise-note">${e.note}</div>`:""}${active.sets.map((s,si)=>`<div class="set-row"><div class="set-number">S${si+1}</div><input class="set-input" type="number" inputmode="decimal" placeholder="${state.unit}" value="${s.weight}" onchange="updateSet(${i},${si},'weight',this.value)"><input class="set-input" type="number" inputmode="numeric" placeholder="reps" value="${s.reps}" onchange="updateSet(${i},${si},'reps',this.value)"><button class="complete-set ${s.completed?"complete":""}" onclick="completeSet(${i},${si},${e.rest})">✓</button></div>`).join("")}${getProgressSuggestion(e)}</section>`}
function updateSet(i,si,field,value){state.activeWorkout.exercises[i].sets[si][field]=value;saveState()}
function completeSet(i,si,rest){const s=state.activeWorkout.exercises[i].sets[si];s.completed=!s.completed;if(s.completed)startTimer(rest);saveState();renderActiveWorkout()}
function toggleCardio(i){state.activeWorkout.exercises[i].cardioCompleted=!state.activeWorkout.exercises[i].cardioCompleted;saveState();renderActiveWorkout()}
let timerInterval=null;function startTimer(seconds){state.timer={end:Date.now()+seconds*1000};saveState();clearInterval(timerInterval);timerInterval=setInterval(updateTimerDisplay,500)}
function renderTimer(){return `<div class="timer-bar"><div><small>⏱ REPOS</small><div id="timerValue" class="timer-value">00:00</div></div><button class="secondary-button" style="width:auto;margin:0" onclick="stopTimer()">PASSER</button></div>`}
function updateTimerDisplay(){if(!state.timer)return;const remaining=Math.max(0,state.timer.end-Date.now());if(remaining<=0){stopTimer();if("vibrate" in navigator)navigator.vibrate([150,80,150]);return}const seconds=Math.ceil(remaining/1000),mins=Math.floor(seconds/60),secs=seconds%60,el=document.getElementById("timerValue");if(el)el.textContent=`${String(mins).padStart(2,"0")}:${String(secs).padStart(2,"0")}`}
function stopTimer(){clearInterval(timerInterval);timerInterval=null;state.timer=null;saveState();renderActiveWorkout()}
function finishWorkout(){const w=getWorkoutById(state.activeWorkout.workoutId),completedWorkout={...state.activeWorkout,completedAt:Date.now(),name:w.name};state.workoutHistory.push(completedWorkout);state.activeWorkout=null;state.timer=null;saveState();setPage("home");alert("🎉 Séance terminée !")}
function cancelWorkout(){if(!confirm("Annuler cette séance ? Les données de cette séance seront perdues."))return;state.activeWorkout=null;state.timer=null;saveState();render()}
function findPreviousExercise(id){for(let i=state.workoutHistory.length-1;i>=0;i--){const ex=state.workoutHistory[i].exercises.find(e=>e.exerciseId===id);if(ex&&ex.sets&&ex.sets.length){const valid=ex.sets.filter(s=>s.weight&&s.reps);if(valid.length)return valid.map(s=>`${s.weight} ${state.unit} × ${s.reps}`).join(" • ")}}return null}
function findPreviousExerciseObject(id){for(let i=state.workoutHistory.length-1;i>=0;i--){const ex=state.workoutHistory[i].exercises.find(e=>e.exerciseId===id);if(ex)return ex}return null}
function getProgressSuggestion(e){const previous=findPreviousExerciseObject(e.id);if(!previous)return"";const valid=previous.sets.filter(s=>Number(s.reps)>=e.maxReps);return valid.length===e.sets?`<div class="exercise-note">🏆 Tu as atteint ${e.maxReps} répétitions sur toutes les séries la dernière fois.<br><br>Essaie une petite augmentation de charge si ta technique était bonne.</div>`:""}
function renderHistory(){title.textContent="Historique";if(!state.workoutHistory.length){main.innerHTML=`<div class="empty-state"><div style="font-size:40px">📅</div><h3>Aucune séance</h3><p>Tes entraînements terminés apparaîtront ici.</p></div>`;return}main.innerHTML=`<section class="card">${[...state.workoutHistory].reverse().map(s=>`<div class="history-item"><div class="history-name">${s.name}</div><div class="history-date">${formatDate(s.completedAt)} • ${Math.round((s.completedAt-s.startedAt)/60000)} min</div></div>`).join("")}</section>`}
function renderProgress(){title.textContent="Progrès";const entries=Object.values(calculateExerciseStats()).sort((a,b)=>b.bestWeight-a.bestWeight);if(!entries.length){main.innerHTML=`<div class="empty-state"><div style="font-size:40px">📈</div><h3>Pas encore de données</h3><p>Termine quelques séances pour voir ta progression.</p></div>`;return}const max=Math.max(...entries.map(e=>e.bestWeight),1);main.innerHTML=entries.map(s=>`<section class="card"><strong>${s.name}</strong><div class="hero-subtitle">Meilleure charge : ${s.bestWeight} ${state.unit}</div><div class="progress-bar-wrap"><div class="progress-bar" style="width:${Math.max(5,s.bestWeight/max*100)}%"></div></div></section>`).join("")}
function calculateExerciseStats(){const stats={};state.workoutHistory.forEach(session=>{const w=getWorkoutById(session.workoutId);session.exercises.forEach(record=>{const ex=w.exercises.find(e=>e.id===record.exerciseId);if(!ex||ex.type!=="strength")return;record.sets.forEach(set=>{const weight=Number(set.weight);if(!weight)return;if(!stats[ex.id])stats[ex.id]={name:ex.name,bestWeight:weight};stats[ex.id].bestWeight=Math.max(stats[ex.id].bestWeight,weight)})})});return stats}
function getPersonalRecordCount(){return Object.keys(calculateExerciseStats()).length}
function openSettings(){modalRoot.innerHTML=`<div class="modal-overlay" onclick="closeModal(event)"><div class="modal"><div class="modal-handle"></div><h2>Paramètres</h2><label>Unité de poids</label><select onchange="changeUnit(this.value)"><option value="lb" ${state.unit==="lb"?"selected":""}>Livres (lb)</option><option value="kg" ${state.unit==="kg"?"selected":""}>Kilogrammes (kg)</option></select><button class="secondary-button" onclick="exportBackup()">📤 Exporter une sauvegarde</button><button class="secondary-button" onclick="document.getElementById('backupInput').click()">📥 Importer une sauvegarde</button><input id="backupInput" type="file" accept=".json" hidden onchange="importBackup(this.files[0])"><button class="secondary-button danger-button" onclick="resetApp()">Effacer toutes les données</button></div></div>`}
function changeUnit(unit){state.unit=unit;saveState();modalRoot.innerHTML="";render()}
function exportBackup(){const data=JSON.stringify(state,null,2),blob=new Blob([data],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`stronger-backup-${Date.now()}.json`;link.click();URL.revokeObjectURL(url)}
function importBackup(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{state=JSON.parse(reader.result);saveState();modalRoot.innerHTML="";render();alert("Sauvegarde restaurée.")}catch{alert("Le fichier de sauvegarde est invalide.")}};reader.readAsText(file)}
function resetApp(){if(!confirm("Effacer tout l’historique et remettre l’application à zéro ?"))return;localStorage.removeItem("stronger_state");state=structuredClone(DEFAULT_STATE);modalRoot.innerHTML="";render()}
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(console.error));
render();
